<?php declare(strict_types=1);

/**
 * Centralized semantic governance registry.
 *
 * This file is internal infrastructure. It is not a CMS, publication system,
 * campaign system, SEO system, or relationship renderer. Public routes may
 * consume only scalar copy that passes VeyluneTheme\Semantic\SemanticRegistry
 * audits.
 */
$semanticTemplateFields = ['displayTitle', 'summaryLabel', 'materialContext', 'spatialContext', 'governanceNote'];
$governedLocales = ['en', 'de'];
$requiredAuthoringReviewGates = [
    'forbidden_vocabulary',
    'synonym_governance',
    'implication',
    'emotional_intensity',
    'multilingual_parity',
    'prestige_escalation',
    'semantic_consistency',
    'semantic_hierarchy',
    'discoverability_implication',
];

return [
    'registryVersion' => 'semver-20.1.0',
    'ownership' => [
        'semanticApprover' => 'constitutional_semantic_governance',
        'rollbackAuthority' => 'constitutional_semantic_governance',
        'auditAuthority' => 'semantic_audit_pipeline',
        'escalationAuthority' => 'constitutional_review',
        'multilingualParityAuthority' => 'semantic_audit_pipeline',
        'deploymentBlockingAuthority' => 'semantic_audit_pipeline',
    ],
    'versioning' => [
        'currentSemanticVersionId' => 'sem-20-1-identity-consolidation-001',
        'rollbackTarget' => 'sem-18-6-centralized-registry-001',
        'deploymentStatus' => 'deployment_gated',
        'riskClassification' => 'controlled_low',
    ],
    'policy' => [
        'routeLocalCopyOwnershipAllowed' => false,
        'freeformEditorialCopyAllowed' => false,
        'directProductionMutationAllowed' => false,
        'newTerminologyWithoutRegistryApprovalAllowed' => false,
        'newSemanticStructuresWithoutConstitutionalApprovalAllowed' => false,
        'semanticReviewBypassAllowed' => false,
        'publicClassificationExposureAllowed' => false,
        'synonymApprovalRequired' => true,
        'emotionallyPersuasiveTermsAllowed' => false,
        'luxurySignalingVocabularyRestricted' => true,
        'failedAuditBlocksDeployment' => true,
        'failedPostDeploymentAuditRequiresRollback' => true,
        'copyChangesAreGovernanceEvents' => true,
    ],
    'limits' => [
        'maxWordsPerField' => 18,
        'maxEmotionalIntensity' => 1,
        'maxPrestigeSensitivity' => 1,
        'maxEscalationSensitivity' => 1,
    ],
    'authoringWorkflow' => [
        'stages' => [
            'draft',
            'semantic_pre_review',
            'semantic_audit',
            'semantic_approval',
            'deployment_ready',
            'deployed',
            'rollback',
            'rejected',
        ],
        'allowedTransitions' => [
            'draft' => ['semantic_pre_review', 'rejected'],
            'semantic_pre_review' => ['semantic_audit', 'draft', 'rejected'],
            'semantic_audit' => ['semantic_approval', 'draft', 'rejected'],
            'semantic_approval' => ['deployment_ready', 'draft', 'rejected'],
            'deployment_ready' => ['deployed', 'rollback'],
            'deployed' => ['rollback'],
            'rollback' => ['draft'],
            'rejected' => ['draft'],
        ],
        'deploymentAuthorizedStates' => ['deployment_ready'],
        'rollbackEntryStates' => ['deployment_ready', 'deployed'],
        'requiredReviewGates' => $requiredAuthoringReviewGates,
        'approvedInterfaces' => [
            'registry_governed_scalar_fields',
            'controlled_vocabulary_registry',
            'semantic_template_fragments',
        ],
        'forbiddenInterfaces' => [
            'route_local_freeform_copy',
            'cms_editorial_body',
            'campaign_copy_surface',
            'public_governance_metadata',
        ],
    ],
    'contributorRoles' => [
        'semantic_contributor' => [
            'mayAuthorDraft' => true,
            'mayReview' => false,
            'mayApprove' => false,
            'mayDeploy' => false,
            'mayRollback' => false,
            'mayOverrideBlocks' => false,
        ],
        'semantic_reviewer' => [
            'mayAuthorDraft' => false,
            'mayReview' => true,
            'mayApprove' => false,
            'mayDeploy' => false,
            'mayRollback' => false,
            'mayOverrideBlocks' => false,
        ],
        'semantic_approver' => [
            'mayAuthorDraft' => false,
            'mayReview' => true,
            'mayApprove' => true,
            'mayDeploy' => false,
            'mayRollback' => false,
            'mayOverrideBlocks' => false,
        ],
        'semantic_deployment_authority' => [
            'mayAuthorDraft' => false,
            'mayReview' => false,
            'mayApprove' => false,
            'mayDeploy' => true,
            'mayRollback' => false,
            'mayOverrideBlocks' => false,
        ],
        'semantic_rollback_authority' => [
            'mayAuthorDraft' => false,
            'mayReview' => false,
            'mayApprove' => false,
            'mayDeploy' => false,
            'mayRollback' => true,
            'mayOverrideBlocks' => false,
        ],
        'semantic_governance_authority' => [
            'mayAuthorDraft' => false,
            'mayReview' => true,
            'mayApprove' => true,
            'mayDeploy' => false,
            'mayRollback' => true,
            'mayOverrideBlocks' => true,
        ],
    ],
    'semanticTemplates' => [
        'edition_scalar_context' => [
            'fields' => $semanticTemplateFields,
            'locales' => $governedLocales,
            'maxFields' => 5,
            'freeformSectionsAllowed' => false,
            'routeLocalExtensionAllowed' => false,
        ],
    ],
    'approvedTerms' => [
        'archive',
        'boundaries',
        'canonical',
        'context',
        'controlled',
        'document',
        'edition',
        'governance',
        'governed',
        'identity',
        'material',
        'mineral',
        'neutral',
        'placement',
        'proportion',
        'public',
        'record',
        'restraint',
        'route',
        'spatial',
        'stable',
        'study',
        'surface',
    ],
    'forbiddenTerms' => [
        'acquire',
        'available',
        'bespoke',
        'buy',
        'campaign',
        'checkout',
        'collect',
        'collectible',
        'collection',
        'concierge',
        'coveted',
        'curated',
        'exceptional',
        'exclusive',
        'inquire',
        'limited',
        'luxury',
        'order',
        'own',
        'partner',
        'purchase',
        'rare',
        'refined',
        'recommend',
        'recommended',
        'reserve',
        'sought-after',
        'shop',
        'signature',
        'story',
        'timeless',
    ],
    'controlledSynonyms' => [
        'governed' => [
            'approved' => ['controlled', 'bounded'],
            'forbidden' => ['curated', 'exclusive', 'prestige'],
        ],
        'record' => [
            'approved' => ['document', 'reference'],
            'forbidden' => ['story', 'chapter', 'feature'],
        ],
        'material' => [
            'approved' => ['surface', 'mineral'],
            'forbidden' => ['precious', 'rare', 'sumptuous'],
        ],
        'spatial' => [
            'approved' => ['placement', 'scale'],
            'forbidden' => ['atmospheric', 'dreamlike', 'immersive'],
        ],
    ],
    'implicationClassifications' => [
        'commercial' => ['severity' => 'blocking', 'rollbackTrigger' => true],
        'editorial' => ['severity' => 'blocking', 'rollbackTrigger' => true],
        'relationship' => ['severity' => 'blocking', 'rollbackTrigger' => true],
        'discoverability' => ['severity' => 'blocking', 'rollbackTrigger' => true],
        'acquisition' => ['severity' => 'blocking', 'rollbackTrigger' => true],
        'prestige' => ['severity' => 'blocking', 'rollbackTrigger' => true],
        'urgency' => ['severity' => 'blocking', 'rollbackTrigger' => true],
        'recommendation' => ['severity' => 'blocking', 'rollbackTrigger' => true],
        'campaign' => ['severity' => 'blocking', 'rollbackTrigger' => true],
    ],
    'classificationTerms' => [
        'commercial' => ['buy', 'shop', 'purchase', 'order', 'checkout', 'price', 'sale', 'own'],
        'editorial' => ['story', 'journal', 'narrative', 'chapter', 'mythology', 'feature'],
        'relationship' => ['partner', 'collaboration', 'supplier', 'atelier', 'official', 'paired with', 'alongside'],
        'discoverability' => ['discover', 'discover more', 'explore', 'explore more', 'search', 'browse', 'seo', 'index'],
        'acquisition' => ['acquire', 'inquire', 'reserve', 'available', 'available soon', 'request', 'private access'],
        'prestige' => ['luxury', 'exclusive', 'rare', 'iconic', 'elevated', 'refined', 'distinguished', 'coveted', 'exceptional', 'sought-after'],
        'urgency' => ['now', 'today', 'limited', 'last', 'soon'],
        'recommendation' => ['recommend', 'recommended', 'recommended alongside', 'selected for you', 'best', 'suggested'],
        'campaign' => ['campaign', 'launch', 'drop', 'release event', 'promotion'],
    ],
    'emotionalIntensityTerms' => [
        'calm' => 1,
        'quiet' => 1,
        'atmospheric' => 2,
        'aspirational' => 3,
        'desirable' => 3,
        'dreamlike' => 3,
        'exceptional' => 3,
        'seductive' => 3,
        'extraordinary' => 3,
    ],
    'prestigeSensitivityTerms' => [
        'refined' => 2,
        'luxury' => 3,
        'exclusive' => 3,
        'distinguished' => 2,
        'exceptional' => 3,
        'rare' => 3,
        'iconic' => 3,
        'prestige' => 3,
        'sought-after' => 3,
    ],
    'escalationSensitivityTerms' => [
        'curated' => 2,
        'editorial' => 2,
        'exceptional' => 2,
        'campaign' => 3,
        'story' => 3,
        'mythology' => 3,
        'aspirational' => 3,
    ],
    'localeMappings' => [
        'en' => [
            'governed' => 'governed',
            'public' => 'public',
            'record' => 'record',
            'material' => 'material',
            'spatial' => 'spatial',
        ],
        'de' => [
            'governed' => 'gesteuertes',
            'public' => 'oeffentliches',
            'record' => 'dokument',
            'material' => 'material',
            'spatial' => 'raum',
        ],
    ],
    'auditHistory' => [
        [
            'semanticVersionId' => 'sem-20-1-identity-consolidation-001',
            'approvedBy' => 'constitutional_semantic_governance',
            'changeReason' => 'Post-marketplace identity language consolidation',
            'affectedRoutes' => ['/editions/{reference}', '/de/editionen/{reference}'],
            'affectedLocales' => ['en', 'de'],
            'implicationAuditResult' => 'required',
            'toneAuditResult' => 'required',
            'rollbackTarget' => 'sem-18-6-centralized-registry-001',
            'deploymentStatus' => 'deployment_gated',
            'semanticRiskClassification' => 'controlled_low',
        ],
        [
            'semanticVersionId' => 'sem-18-6-centralized-registry-001',
            'approvedBy' => 'constitutional_semantic_governance',
            'changeReason' => 'Phase 18.6 centralized semantic infrastructure implementation',
            'affectedRoutes' => ['/editions/{reference}', '/de/editionen/{reference}'],
            'affectedLocales' => ['en', 'de'],
            'implicationAuditResult' => 'required',
            'toneAuditResult' => 'required',
            'rollbackTarget' => 'sem-18-4-single-route-enrichment-001',
            'deploymentStatus' => 'deployment_gated',
            'semanticRiskClassification' => 'controlled_low',
        ],
    ],
];
